version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    enabled: false
  similar-code:
    enabled: false
  file-lines:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  identical-code:
    enabled: false
plugins:
  csslint:
    enabled: true
    checks:
      box-sizing:
        enabled: false
      star-property-hack:
        enabled: false
      adjoining-classes:
        enabled: false
      ids:
        enabled: false
  markdownlint:
    enabled: true
  eslint:
    enabled: true
    no-unused-expressions:
      enabled: false
    checks:
      complexity:
        enabled: false
      max-statements:
        enabled: false
exclude_patterns:
- "**/dist/"
- "**/build/"
- "**/test/"
- "**/lib/"
- "**/themes/"