addons: 
  apt:
    packages:
      - graphviz
before_cache: 
  - "rm -rf $HOME/.m2/repository/org/ligoj/app"
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
before_install: 
  - "chmod +x ./travis.sh"
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
    - $HOME/jvm
    - $HOME/maven
env: 
  - TARGET=BUILD
branches:
  only:
    - master
    - dev
install: /bin/true 
jdk: oraclejdk9
language: java
notifications: 
  email: false
script: "./travis.sh"
sudo: false
