addons: 
  apt:
    packages:
      - graphviz
before_cache: 
  - "find $HOME/.m2 -name resolver-status.properties -exec rm {} \\;"
before_install:
  - "chmod +x ./travis.sh"
  - rm "${JAVA_HOME}/lib/security/cacerts"
  - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
install: java --version 
cache: 
  directories: 
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
    - $HOME/.cache
    - $HOME/maven
jdk: openjdk11
env: 
  - TARGET=BUILD
branches:
  only:
    - master
    - dev
language: java
notifications: 
  email: false
sudo: false
script: "./travis.sh"
