<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.ligoj.api</groupId>
        <artifactId>plugin-parent</artifactId>
        <version>5.0.0</version>
        <relativePath />
    </parent>

    <groupId>org.ligoj.plugin</groupId>
    <artifactId>plugin-vm-azure</artifactId>
    <version>2.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>Ligoj - Plugin VM Azure</name>

    <scm>
        <connection>scm:git:https://github.com/ligoj/plugin-vm-azure</connection>
        <developerConnection>scm:git:https://github.com/ligoj/plugin-vm-azure</developerConnection>
        <url>https://github.com/ligoj/plugin-vm-azure.git</url>
    </scm>

    <dependencies>
        <dependency>
            <groupId>org.ligoj.plugin</groupId>
            <artifactId>plugin-vm</artifactId>
            <version>[3.0.0-SNAPSHOT,3.1.0)</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>github</id>
            <distributionManagement>
                <repository>
                    <id>github-ligoj</id>
                    <name>GitHub Packages</name>
                    <url>https://maven.pkg.github.com/ligoj/plugin-vm-azure</url>
                </repository>
            </distributionManagement>
        </profile>
    </profiles>
</project>